services:
  sqlserverdb:
    build:
      context: .
      dockerfile_inline: |
        FROM mcr.microsoft.com/mssql/server:2022-latest
        COPY ./ScriptFilmes.sql /etc/data/ScriptFilmes.sql
        ENV ACCEPT_EULA=Y
        ENV MSSQL_SA_PASSWORD=P@ssw0rd
        ENV MSSQL_PID=Developer
        RUN /opt/mssql/bin/sqlservr & (sleep 10 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rd' -i /etc/data/ScriptFilmes.sql)
    ports:
      - 1433:1433
